// <auto-generated />
using Libreria;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TestWebApi.Migrations
{
    [DbContext(typeof(LibroDB))]
    partial class LibroDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Libreria.Libro", b =>
                {
                    b.Property<string>("genere")
                        .HasColumnType("TEXT");

                    b.Property<int>("anno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("autore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("genere");

                    b.ToTable("Libri");
                });
#pragma warning restore 612, 618
        }
    }
}
